### ISSUE TITLE
Lte band mask calculate

### ISSUE THREAD

**Issue by szyper-sakrona** [danielewood/sierra-wireless-modems#1]
Hello, I'd like to thank you for this resources - priceless!!!
And give you an idea to inform how to add (simply hex calc) lte band mask. In my country I have b3+b7+b20  - so I had to create custom entry.
Thanks a lot!

**Comment by danielewood** [comment]
Thanks for the suggestion. 
Section added as [How to Calculate Bitmasks to Lock LTE Bands](https://github.com/danielewood/sierra-wireless-modems#how-to-calculate-bitmasks-to-lock-lte-bands).

**Comment by szyper-sakrona** [comment]
Thanks for detailed explanation. There is (only for me) an idea - why you mix bands - i just added a new entry with B3+B7+B20 mask, and then lock this with command AT!BAND=... at the end of you text there is lock to 10 socket - AT!BAND=09 - is that right? it will works?
Btw. the command AT!LTECA? is not (currently) supported on my em7565 modem.
But performance id outstanding with 3xCA over my older mc7455.
With mc7455 with every firmware update I have to restore QPST backup, because my calibration data was lost. Anyway em7565 is much simpler!
Thanks!!!

**Comment by danielewood** [comment]
I did the mix in that example to demonstrate band-locking across multiple columns, as all other examples are a single column.

That said. I do not band lock at all unless I am specifically trying to avoid a carrier at a fixed location. For example, if there was a 5MHz B5 carrier available on the closest tower, but a further distant tower had 40MHz of B2+B12+B30. I might decide to lock to that band set if the signal was still acceptable, as it would result in far higher speeds.

I picked slot 10 because it is the first un-used slot available.

I'm not sure when or if LTECA will come to the 7565. I only discovered it as a passing remark in a changelog for the 7455.
