### ISSUE TITLE
Setup without external enclosure

### ISSUE THREAD

**Issue by jamesadney** [danielewood/sierra-wireless-modems#12]
Hi, thanks for all your work on this repo!

I have a Thinkpad T460s and I'd like to install the card internally. The README says that the instructions only work for an external USB enclosure. Is it not possible to setup the modem when it's installed internally, or would it just requiring modifying the procedure?

**Comment by njang** [comment]
**Disclaimer**: I'm following this repo, without actually having done any of the work yet. As such, the response below is an untested speculation, based on my past experience with other Thinkpad models. It'd be great to hear from Daniel or others confirm or correct this.

Do you have a Lenovo branded modem? If yes, you should be able to install it internally without needing the external USB enclosure, and not have to deal with BIOS throwing 1802 error (more on this later). Otherwise, the recommended modem for T460s (which I also have) is _Dell DW5811e_ for stated reasons. ([Which Modem to Buy](https://github.com/danielewood/sierra-wireless-modems#which-modem-to-buy))

Generally speaking, (a) Thinkpad will not allow booting with the unauthorized (non-Lenovo) modem installed internally, and (b) an internal slot cannot accept modem being hot-swapped post-boot. Using external USB enclosure must be a work-around for this, such that the modem's firmware can be modified using the script mentioned ([Change Modem Identity (Sierra Wireless / Lenovo / Dell)](https://github.com/danielewood/sierra-wireless-modems#change-modem-identity-sierra-wireless--lenovo--dell)). 

Once the identity has been set to Lenovo, whitelist shouldn't complain with it being internally installed. For additional reference, here's ThinkWiki's article on 1802 error message. ([Problem with unauthorized MiniPCI network card - ThinkWiki](http://www.thinkwiki.org/wiki/Problem_with_unauthorized_MiniPCI_network_card))

Hope this helps, and keep us posted. Thanks,

**Comment by jamesadney** [comment]
@njang Thanks for the reply! That makes perfect sense. I also have the Dell modem. We'll see how it goes with the USB adapter :crossed_fingers:

**Comment by jamesadney** [comment]
Just a brief update: I was able to update the firmware and change the modem identity with a USB adapter. Then it works as expected after installing it internally.

I didn't try booting with the modem installed internally before changing the identity because I'm quite sure that @njang is right about it being blacklisted. And I didn't even want to try hot swapping it.
