### ISSUE TITLE
Can Lenovo branded EM7455 change identities?

### ISSUE THREAD

**Issue by bilogic** [danielewood/sierra-wireless-modems#121]
Hi!

Can Lenovo branded ones have their identities changed? Or only the Dell ones allow for it? Thank you.

**Comment by danielewood** [comment]
Brand identities do not matter except to Laptops and Windows driver packages.

Any modem can be any identity, even the entirely wrong identity (You can make a Lenovo 7455 appear as a Dell 7430, but that will probably just break things because the 7430 drivers wont initialize the 7455 properly(Or it might, never tested that)).
