### ISSUE TITLE
Correct method for latest firmware...

### ISSUE THREAD

**Issue by oleteacher** [danielewood/sierra-wireless-modems#41]
This may seem like a simple question to you Linux guru's, but please remember not all of us are :)

In the `autoflash-7455.sh` script, could I have example of using latest firmware SWI9X30C_02.33.03.00_Generic_002.072_000.zip (least current at time of this post)?

Not positive where to update the `autoflash-7455.sh` and hate to ASSume ...

I thank you in advance!

**Comment by danielewood** [comment]
See the following section of autoflash:
https://github.com/danielewood/sierra-wireless-modems/blob/15a8ee74bfc3ab7f317b8e8a8cfa56c99c81a4c5/autoflash-7455.sh#L294-L299

It will always pull the most current version by performing some badly written grep/awk code. Currently it pulls: SWI9X30C_02.33.03.00_GENERIC_002.072_000.zip


You can always override what it pulls by manually specifying a filename for the firmware, such as:
`SWI9X30C_ZIP="SWI9X30C_02.30.01.01_GENERIC_002.045_001.zip" sudo bash autoflash-7455.sh`

Otherwise, if you run the script without specifying which firmware you want, it will always attempt the latest.

**Comment by oleteacher** [comment]
Perfect, thank you very much. Trying some experiments for advance coding in classroom (not virtual) and this actually fun for students:)
